Repository Chanjnint21/OutdoorTraveler, pull requests merged in 2023-08, with the labels that each got.

#65 added feature(SearchUser and visit User)
  public/favicon.ico
  public/index.html
  src/components/RegisterDialog.vue
  src/components/userCard.vue
  src/db.json
  src/router/index.js
  src/service/index.js
  src/views/HomeView.vue
  src/views/Profile/FavoritePost.vue
  src/views/Profile/JoinedTrip.vue
  src/views/Profile/ProfileView.vue
  src/views/Profile/UpComing.vue
  src/views/Profile/YourBlog.vue
  src/views/Trip/Component/FormComponent.vue
  src/views/layout/AppLayout.vue
Labels: documentation, enhancement, feature

#67 Follower & Verification
  src/components/CardComponent.vue
  src/components/userCard.vue
  src/db.json
  src/service/index.js
  src/views/HomeView.vue
  src/views/Profile/ProfileView.vue
  src/views/Trip/Component/FormComponent.vue
Labels: documentation, enhancement

#68 feat(badge): badge count days & ViewCard Icon
  src/components/CardComponent.vue
  src/components/ViewCard.vue
  src/db.json
Labels: documentation, feature

#70 Register
  src/components/ButtonComponent.vue
  src/router/index.js
  src/views/Auth/AdditionalInfo.vue
  src/views/Auth/LoginView.vue
  src/views/Auth/ProfileInfo.vue
  src/views/Auth/RegisterView.vue
  src/views/Auth/personalInfo.vue
  src/views/HomeView.vue
Labels: documentation, enhancement

#73 Fully Functional Register
  src/components/CardComponent.vue
  src/service/index.js
  src/views/Auth/AdditionalInfo.vue
  src/views/Auth/ProfileInfo.vue
  src/views/Auth/RegisterView.vue
  src/views/Auth/personalInfo.vue
  src/views/Profile/components/ProfDialog.vue
Labels: documentation, enhancement

#75 Fixing(Validate):EndDate
  src/components/ButtonComponent.vue
  src/components/CardComponent.vue
  src/components/DatePicker.vue
  src/db.json
  src/views/HomeView.vue
  src/views/Profile/ProfileView.vue
  src/views/Trip/Component/FormComponent.vue
Labels: enhancement

#76 Newfeature and fixing error
  src/assets/Img/404.png
  src/assets/css/stylesheet.css
  src/assets/empty_box.png
  src/components/ButtonComponent.vue
  src/components/CardComponent.vue
  src/components/RegisterDialog.vue
  src/db.json
  src/views/Auth/AdditionalInfo.vue
  src/views/Auth/LoginView.vue
  src/views/Auth/ProfileInfo.vue
  src/views/Auth/RegisterView.vue
  src/views/Auth/personalInfo.vue
  src/views/HomeView.vue
  src/views/NotFound.vue
  src/views/Profile/JoinedTrip.vue
  src/views/Profile/ProfileView.vue
  src/views/Profile/UpComing.vue
  src/views/Profile/components/ProfDialog.vue
  src/views/layout/AppLayout.vue
Labels: documentation, feature

#83 added Image and name to Follwer and following
  src/service/index.js
  src/views/Profile/components/FollowComponent.vue
  src/views/Profile/components/FollowerComponent.vue
Labels: documentation, feature
