Repository Chanjnint21/OutdoorTraveler, pull requests merged in 2023-06, with the labels that each got.

#1 Add Vuetify Plugin
  package.json
  public/index.html
  src/App.vue
  src/assets/logo.svg
  src/components/HelloWorld.vue
  src/main.js
  src/plugins/vuetify.js
  src/views/HomeView.vue
  vue.config.js
  yarn.lock
Labels: feature

#2 add-libraries
  package.json
  yarn.lock
Labels: feature

#3 adding-mdi/font
  package.json
  yarn.lock
Labels: feature

#4 Add Router files
  src/App.vue
  src/router/index.js
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/NotFound.vue
  src/views/ProfileView.vue
  src/views/TripCreate.vue
Labels: feature

#9 Add source code to trip create
  src/components/FileField.vue
  src/components/TextField.vue
  src/main.js
  src/views/LoginView.vue
  src/views/TripCreate.vue
Labels: feature

#11 views(profile):update
  src/assets/CoverImage.jpeg
  src/assets/pf1.jpeg
  src/components/ButtonComponent.vue
  src/components/CardComponent.vue
  src/main.js
  src/views/HomeView.vue
  src/views/ProfileView.vue
Labels: feature

#10 Add responsive to HomeView.vue
  src/components/ButtonComponent.vue
  src/router/index.js
  src/views/HomeView.vue
  src/views/layout/AppLayout.vue
Labels: feature

#12 Fixed SelectField
  src/components/ButtonComponent.vue
  src/components/SelectField.vue
  src/components/TextField.vue
  src/views/TripCreate.vue
Labels: documentation

#13 feat(Home/Profile):fixed-card
  src/components/CardComponent.vue
  src/views/HomeView.vue
  src/views/ProfileView.vue
Labels: feature

#22 Apply feedback
  src/components/ButtonComponent.vue
  src/components/CardComponent.vue
  src/components/RangeSliderField.vue
  src/components/SelectField.vue
  src/components/TextArea.vue
  src/components/TextField.vue
  src/main.js
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/ProfileView.vue
  src/views/TripCreate.vue
  src/views/layout/AppLayout.vue
Labels: documentation

#23 Change colors
  src/assets/Img/logo1687A7.png
  src/assets/Img/logo276678.png
  src/assets/Img/logoD3E0EA.png
  src/assets/Img/logoF6F5F5.png
  src/components/ButtonComponent.vue
  src/components/CardComponent.vue
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/ProfileView.vue
  src/views/TripCreate.vue
  src/views/layout/AppLayout.vue
Labels: documentation, feature

#26 DB(add fake tripcard data)
  src/db.json
Labels: documentation

#28 Feat(Homepage):Searching-Card
  db.json
  src/views/HomeView.vue
Labels: feature

#30 Feat(HomePage&Service):replacing-JSONData
  src/components/CardComponent.vue
  src/service/index.js
  src/views/HomeView.vue
Labels: enhancement

#31 Updated component and Tripcreate post request
  src/Model/tripcard.js
  src/components/DatePicker.vue
  src/components/FileField.vue
  src/components/RangeSliderField.vue
  src/components/SelectField.vue
  src/components/TextArea.vue
  src/components/TextField.vue
  src/components/TimePicker.vue
  src/main.js
  src/views/LoginView.vue
  src/views/TripCreate.vue
  src/views/layout/AppLayout.vue
Labels: documentation

#33 Move HTTP request to service and fixed error
  src/components/ButtonComponent.vue
  src/components/TimePicker.vue
  src/router/index.js
  src/service/index.js
  src/views/LoginView.vue
  src/views/TripCreate.vue
  src/views/layout/AppLayout.vue
Labels: documentation

#34 Added Sorting function and some stylesheet
  src/Model/tripcard.js
  src/components/ButtonComponent.vue
  src/components/CardComponent.vue
  src/components/VueLoad.vue
  src/db.json
  src/main.js
  src/service/index.js
  src/views/HomeView.vue
  src/views/TripCreate.vue
  src/views/layout/AppLayout.vue
Labels: documentation, enhancement
